import { Code, Brain, Scale, BookOpen, DollarSign } from "lucide-react";
import type { Benchmarks, Model, Task, Budget } from "./types";

export const MODELS: readonly Model[] = [
  {
    id: "gpt54mini",
    name: "GPT-5.4 mini",
    provider: "OpenAI",
    context: 400000,
    maxOutput: 128000,
    pricingTiers: [{ upTo: null, inputCost: 0.75, outputCost: 4.50, cachedInputCost: 0.075, cacheWriteCost: null }],
    speed: "fast",
    strengths: ["Fast inference", "Great cost-performance ratio", "Strong coding", "Computer use", "400K context"],
    bestFor: ["High-volume tasks", "Chatbots", "Code generation", "Balanced workloads", "Agentic subagents"],
    idealInput: "Structured prompts, concise instructions, JSON schemas, code snippets",
    idealOutput: "Quick responses, code completions, classifications, structured JSON",
    tier: "mid",
    color: "#10a37f",
    benchmarks: { sweProVerified: 65, arenaOverall: 72, arenaCoding: 70, mmluPro: 68, aime: 45 },
  },
  {
    id: "gpt54",
    name: "GPT-5.4",
    provider: "OpenAI",
    context: 1050000,
    maxOutput: 16384,
    pricingTiers: [
      { upTo: 272000, inputCost: 2.50, outputCost: 15.00, cachedInputCost: 0.25, cacheWriteCost: null },
      { upTo: null, inputCost: 5.00, outputCost: 22.50, cachedInputCost: 0.50, cacheWriteCost: null },
    ],
    speed: "medium",
    strengths: ["Flagship reasoning", "Computer use API", "Configurable reasoning effort", "Strong across all benchmarks", "Agentic workflows"],
    bestFor: ["General-purpose flagship", "Complex reasoning", "Long document analysis", "Professional tasks", "Multi-step workflows"],
    idealInput: "Detailed instructions, multi-turn conversations, documents up to 1M tokens, system prompts with reasoning effort config",
    idealOutput: "Thorough analysis, nuanced writing, structured reports, detailed explanations",
    tier: "premium",
    color: "#10a37f",
    benchmarks: { sweProVerified: 78, arenaOverall: 88, arenaCoding: 82, mmluPro: 89, aime: 85 },
    reasoningEffort: ["none", "low", "medium", "high", "xhigh"],
  },
  {
    id: "gpt53codex",
    name: "GPT-5.3 Codex",
    provider: "OpenAI",
    context: 400000,
    maxOutput: 16384,
    pricingTiers: [{ upTo: null, inputCost: 1.75, outputCost: 14.00, cachedInputCost: 0.175, cacheWriteCost: null }],
    speed: "medium",
    strengths: ["Top-tier code generation", "Terminal-heavy workflows", "Codex agent integration", "400K context for large codebases"],
    bestFor: ["Software development", "Code review", "Debugging", "Codebase refactoring", "Agent-driven coding"],
    idealInput: "Code files, error logs, terminal output, repository context, diff patches",
    idealOutput: "Code implementations, bug fixes, refactored code, test suites, technical documentation",
    tier: "mid",
    color: "#10a37f",
    benchmarks: { sweProVerified: 76, arenaOverall: 75, arenaCoding: 88, mmluPro: 72, aime: 60 },
    legacy: true,
    reasoningEffort: ["low", "medium", "high", "xhigh"],
  },
  {
    id: "opus46",
    name: "Opus 4.6",
    provider: "Anthropic",
    context: 1000000,
    maxOutput: 128000,
    pricingTiers: [{ upTo: null, inputCost: 5.00, outputCost: 25.00, cachedInputCost: 0.50, cacheWriteCost: 6.25 }],
    speed: "slow",
    strengths: ["Deepest reasoning", "1M token context", "Extended thinking", "Agent teams", "Highest accuracy on complex tasks"],
    bestFor: ["Premium reasoning", "Research & analysis", "Legal & scientific review", "Complex multi-step problems", "Large codebase comprehension"],
    idealInput: "Long documents, research papers, complex multi-part questions, extended thinking tasks, entire codebases",
    idealOutput: "Deep analysis, nuanced reasoning chains, comprehensive reports, research synthesis",
    tier: "premium",
    color: "#d97706",
    benchmarks: { sweProVerified: 80, arenaOverall: 90, arenaCoding: 84, mmluPro: 92, aime: 88 },
    reasoningEffort: ["low", "medium", "high", "max"],
  },
  {
    id: "sonnet46",
    name: "Sonnet 4.6",
    provider: "Anthropic",
    context: 1000000,
    maxOutput: 64000,
    pricingTiers: [{ upTo: null, inputCost: 3.00, outputCost: 15.00, cachedInputCost: 0.30, cacheWriteCost: 3.75 }],
    speed: "fast",
    strengths: ["Excellent coding", "1M context", "Fast inference", "Strong agentic performance", "Computer use"],
    bestFor: ["Coding assistants", "Balanced general tasks", "Agent workflows", "Long document processing", "Content creation"],
    idealInput: "Clear instructions, code context, structured prompts, few-shot examples",
    idealOutput: "Clean code, well-structured text, precise JSON, detailed but concise analysis",
    tier: "mid",
    color: "#d97706",
    benchmarks: { sweProVerified: 79.6, arenaOverall: 82, arenaCoding: 85, mmluPro: 78, aime: 65 },
    reasoningEffort: ["low", "medium", "high"],
  },
  {
    id: "gemini31pro",
    name: "Gemini 3.1 Pro",
    provider: "Google",
    context: 1048576,
    maxOutput: 65536,
    pricingTiers: [
      { upTo: 200000, inputCost: 2.00, outputCost: 12.00, cachedInputCost: 0.20, cacheWriteCost: null },
      { upTo: null, inputCost: 4.00, outputCost: 18.00, cachedInputCost: 0.40, cacheWriteCost: null },
    ],
    speed: "medium",
    strengths: ["Multimodal (text, image, video, audio)", "1M context", "Three-tier thinking", "Competitive pricing", "Strong benchmarks"],
    bestFor: ["Long document analysis", "Multimodal tasks", "Research", "Code generation", "General-purpose work"],
    idealInput: "Mixed media inputs, long documents, images with text, structured analysis requests",
    idealOutput: "Comprehensive analysis, multimodal responses, structured data extraction, detailed summaries",
    tier: "mid",
    color: "#4285f4",
    benchmarks: { sweProVerified: 75, arenaOverall: 80, arenaCoding: 78, mmluPro: 82, aime: 70 },
  },
  {
    id: "kimik25",
    name: "Kimi K2.5",
    provider: "Moonshot AI",
    context: 256000,
    maxOutput: 16384,
    pricingTiers: [{ upTo: null, inputCost: 0.60, outputCost: 3.00, cachedInputCost: 0.10, cacheWriteCost: null }],
    speed: "fast",
    strengths: ["Frontier-level coding benchmarks", "Extremely cost-effective", "Multimodal", "Strong agentic performance"],
    bestFor: ["Budget coding", "High-volume tasks", "Cost-sensitive production", "Agentic workflows", "Multimodal processing"],
    idealInput: "Code context, structured prompts, images, concise task descriptions",
    idealOutput: "Code implementations, structured responses, quick completions",
    tier: "budget",
    color: "#7c3aed",
    benchmarks: { sweProVerified: 76.8, arenaOverall: 70, arenaCoding: 78, mmluPro: 65, aime: 55 },
  },
  {
    id: "glm5",
    name: "GLM-5",
    provider: "Zhipu AI",
    context: 200000,
    maxOutput: 16384,
    pricingTiers: [{ upTo: null, inputCost: 1.00, outputCost: 3.20, cachedInputCost: 0.20, cacheWriteCost: null }],
    speed: "medium",
    strengths: ["Strong math/reasoning", "MIT open source", "744B parameters", "Trained on Ascend (no NVIDIA dependency)"],
    bestFor: ["Math & reasoning", "Open-source deployment", "Research", "Code generation", "Self-hosted inference"],
    idealInput: "Mathematical problems, research questions, code context, structured reasoning tasks",
    idealOutput: "Step-by-step solutions, code implementations, research analysis, structured proofs",
    tier: "mid",
    color: "#06b6d4",
    benchmarks: { sweProVerified: 77.8, arenaOverall: 74, arenaCoding: 72, mmluPro: 85, aime: 92.7 },
  },
  {
    id: "grok420",
    name: "Grok 4.20",
    provider: "xAI",
    context: 2000000,
    maxOutput: 32768,
    pricingTiers: [{ upTo: null, inputCost: 2.00, outputCost: 6.00, cachedInputCost: 0.20, cacheWriteCost: null }],
    speed: "medium",
    strengths: ["2M context window", "Multi-agent (4 Agents)", "Native multimodal", "Low hallucination rate", "Strong coding"],
    bestFor: ["Massive document analysis", "Multi-agent workflows", "Multimodal tasks", "Code generation", "Long context research"],
    idealInput: "Very long documents, multi-file codebases, images with text, complex multi-step instructions",
    idealOutput: "Comprehensive analysis, code implementations, multimodal responses, detailed research synthesis",
    tier: "mid",
    color: "#ef4444",
    benchmarks: { sweProVerified: 78.4, arenaOverall: 78, arenaCoding: 80, mmluPro: 80, aime: 72 },
  },
  {
    id: "qwen35",
    name: "Qwen 3.5",
    provider: "Alibaba",
    context: 1000000,
    maxOutput: 16384,
    pricingTiers: [
      { upTo: 256000, inputCost: 0.40, outputCost: 2.40, cachedInputCost: 0.04, cacheWriteCost: null },
      { upTo: null, inputCost: 0.50, outputCost: 3.00, cachedInputCost: 0.05, cacheWriteCost: null },
    ],
    speed: "fast",
    strengths: ["Best value frontier model", "Native multimodal", "201 languages", "Apache 2.0 open-weight", "1M extended context"],
    bestFor: ["Budget frontier tasks", "Multilingual processing", "Multimodal analysis", "High-volume production", "Open-weight deployment"],
    idealInput: "Multilingual content, images with text, structured prompts, batch processing tasks",
    idealOutput: "Translations, multimodal analysis, structured JSON, code implementations, concise summaries",
    tier: "budget",
    color: "#6366f1",
    benchmarks: { sweProVerified: 77, arenaOverall: 76, arenaCoding: 75, mmluPro: 87.8, aime: 91.3 },
  },
  {
    id: "gemini3flash",
    name: "Gemini 3 Flash",
    provider: "Google",
    context: 1048576,
    maxOutput: 66000,
    pricingTiers: [{ upTo: null, inputCost: 0.50, outputCost: 3.00, cachedInputCost: 0.05, cacheWriteCost: null }],
    speed: "fast",
    strengths: ["Sub-second latency", "1M context", "75% cheaper than Pro", "Strong agentic performance", "Best value in Gemini lineup"],
    bestFor: ["Agentic workflows", "High-volume production", "Budget coding", "Fast inference tasks", "Cost-sensitive applications"],
    idealInput: "Code context, structured prompts, agentic tool calls, batch processing tasks",
    idealOutput: "Fast code completions, structured responses, tool call results, quick summaries",
    tier: "budget",
    color: "#4285f4",
    benchmarks: { sweProVerified: 78, arenaOverall: 73, arenaCoding: 76, mmluPro: 74, aime: 58 },
  },
  {
    id: "minimax27",
    name: "MiniMax 2.7",
    provider: "MiniMax",
    context: 204800,
    maxOutput: 16384,
    pricingTiers: [{ upTo: null, inputCost: 0.30, outputCost: 1.20, cachedInputCost: null, cacheWriteCost: null }],
    speed: "fast",
    strengths: ["Ultra low cost", "Ultra-efficient 10B architecture", "GPT-4 class quality", "Self-improving architecture", "Automatic prompt caching"],
    bestFor: ["High-volume production", "Budget-conscious apps", "Document summarization", "Chatbots", "Classification tasks"],
    idealInput: "Long documents, high-volume batch processing, simple to moderate complexity tasks",
    idealOutput: "Quick classifications, summaries, structured data, chat responses",
    tier: "budget",
    color: "#ec4899",
    benchmarks: { sweProVerified: 56, arenaOverall: 60, arenaCoding: 55, mmluPro: 58, aime: 35 },
  },
] as const;

export const TASKS: readonly Task[] = [
  { id: "coding", label: "Coding & Development", icon: Code },
  { id: "reasoning", label: "Premium Reasoning", icon: Brain },
  { id: "general", label: "Balanced General Use", icon: Scale },
  { id: "longdocs", label: "Long Document Processing", icon: BookOpen },
  { id: "lowcost", label: "Low Cost / High Volume", icon: DollarSign },
];

export const BUDGETS: readonly Budget[] = [
  { id: "tight", label: "Tight", desc: "< $1/M blended" },
  { id: "moderate", label: "Moderate", desc: "$1–$5/M blended" },
  { id: "flexible", label: "Flexible", desc: "$5–$15/M blended" },
  { id: "unlimited", label: "Unlimited", desc: "Best quality, any cost" },
];

export const SPEEDS = [
  { id: "any", label: "Any Speed" },
  { id: "fast", label: "Fast Only" },
  { id: "medium", label: "Medium+" },
] as const;

export const CONTEXTS = [
  { id: "any", label: "Any Size" },
  { id: "small", label: "< 200K" },
  { id: "medium", label: "200K–500K" },
  { id: "large", label: "500K+" },
] as const;
